name: CI

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - uses: teneplaysofficial/diff@d7e5233000c5b461840bced94cd16494e11c9be6 # v1
        with:
          run: |
            pnpm build:schema
            pnpm fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm lint
          pnpm fmt:check
